#!/data/data/com.termux/files/usr/bin/sh
set -eu
export PREFIX=/data/data/com.termux/files/usr
export PATH="$PREFIX/bin:$PATH"
umask 077
exec svlogd -tt "$HOME/.local/state/aircon-central/service-log"
