#!/data/data/com.termux/files/usr/bin/sh
set -eu
export PREFIX=/data/data/com.termux/files/usr
export PATH="$PREFIX/bin:$PATH"
umask 077
exec 2>&1
exec "$PREFIX/bin/python" "$HOME/services/aircon-public-tunnel/current/tunnel.py"
